Repository W170/talenta.magneto365.ui, pull requests merged in 2024-03, with the labels that each got.

#134 Fix/empty results rollback
  src/components/UI/molecules/EmptyResults/EmptyResults.component.tsx
  src/components/UI/molecules/EmptyResults/EmptyResults.interface.ts
  src/components/UI/molecules/EmptyResults/EmptyResults.module.scss
  src/constants/stories/emptyResults.constants.ts
Labels: bug

#135 feat: add keywords logic to vacant details
  src/assets/tag.svg
  src/components/UI/molecules/JobDetails/JobDetails.component.tsx
  src/constants/icons.constants.ts
  src/constants/stories/vacancies.constants.ts
Labels: enhancement

#136 feat: seo improvements in magneto.ui
  src/components/UI/molecules/JobCard/JobCard.interface.ts
  src/components/UI/molecules/JobCardDesktop/JobCardDesktop.component.tsx
  src/components/UI/molecules/JobCardDesktop/JobCardDesktop.module.scss
  src/components/UI/molecules/JobCardMobile/JobCardMobile.component.tsx
  src/components/UI/molecules/Pagination/Pagination.component.tsx
  src/components/UI/molecules/Pagination/Pagination.interface.ts
  src/components/UI/molecules/Pagination/children/BtnPagination.module.scss
  src/components/UI/molecules/Pagination/children/BtnPagination.tsx
  src/components/UI/page/JobsPage/JobsPage.component.tsx
  src/components/UI/page/JobsPage/JobsPage.interface.ts
Labels: enhancement

#137 Feat/infinity scroll
  src/components/UI/molecules/JobCard/children/JobCardSkeleton.component.tsx
  src/components/UI/molecules/JobCard/children/JobCardSkeleton.interface.ts
  src/components/UI/organism/JobDetailsDrawer/JobDetailsDrawer.module.scss
  src/components/UI/page/SuggestedJobsPage/SuggestedJobsPage.component.tsx
  src/components/UI/page/SuggestedJobsPage/SuggestedJobsPage.module.scss
  src/constants/stories/vacancies.constants.ts
Labels: bug, enhancement

#138 feat: update anchors url in vacancies titles and pagination
  src/components/UI/molecules/JobCard/JobCard.interface.ts
  src/components/UI/molecules/JobCardDesktop/JobCardDesktop.component.tsx
  src/components/UI/molecules/JobCardMobile/JobCardMobile.component.tsx
  src/components/UI/page/JobsPage/JobsPage.component.tsx
  src/components/UI/page/JobsPage/JobsPage.interface.ts
Labels: bug

#139 fix: infinity scroll
  src/components/UI/page/SuggestedJobsPage/SuggestedJobsPage.component.tsx
Labels: bug
