Repository W170/talenta.magneto365.ui, pull requests merged in 2024-05, with the labels that each got.

#154 Feat/inmediate hiring
  src/assets/Urgent.svg
  src/components/UI/molecules/JobCard/JobCard.interface.ts
  src/components/UI/molecules/JobCardDesktop/JobCardDesktop.component.tsx
  src/components/UI/molecules/JobCardDesktop/JobCardDesktop.module.scss
  src/constants/icons.constants.ts
  src/constants/stories/vacancies.constants.ts
Labels: enhancement

#156 Feat/drawer width
  src/components/UI/molecules/Drawer/Drawer.component.tsx
  src/components/UI/molecules/Drawer/Drawer.interface.ts
Labels: enhancement

#157 Feat/date picker mobile
  src/components/UI/atoms/DateOptions/DateOptions.interface.ts
  src/components/UI/atoms/DateOptions/DateOptions.module.scss
  src/components/UI/atoms/DateOptions/DateOptions.stories.tsx
  src/components/UI/atoms/DateOptions/DateOptions.tsx
  src/components/UI/atoms/DateOptions/index.ts
  src/components/UI/atoms/FloatingLabel/FloatingLabel.component.tsx
  src/components/UI/atoms/FloatingLabel/FloatingLabel.interface.ts
  src/components/UI/atoms/FloatingLabel/FloatingLabel.module.scss
  src/components/UI/atoms/FloatingLabel/FloatingLabel.stories.tsx
  src/components/UI/atoms/FloatingLabel/index.ts
  src/components/UI/molecules/DateSelection/DateSelection.component.tsx
  src/components/UI/molecules/DateSelection/DateSelection.interface.ts
  src/components/UI/molecules/DateSelection/DateSelection.module.scss
  src/components/UI/molecules/DateSelection/DateSelection.stories.tsx
  src/components/UI/molecules/DateSelection/index.ts
  src/components/UI/organism/MobileDatePicker/MobileDatePicker.component.tsx
  src/components/UI/organism/MobileDatePicker/MobileDatePicker.interface.ts
  src/components/UI/organism/MobileDatePicker/MobileDatePicker.module.scss
  src/components/UI/organism/MobileDatePicker/MobileDatePicker.stories.tsx
  src/components/UI/organism/MobileDatePicker/index.ts
  src/constants/stories/DatePicker.constants.ts
Labels: enhancement

#155 fix: fix UI/UX analyst components
  src/components/UI/atoms/Icon/Icon.component.tsx
  src/components/UI/atoms/Icon/Icon.interface.ts
  src/components/UI/atoms/Logo/Logo.component.tsx
  src/components/UI/atoms/Logo/Logo.interface.ts
  src/components/UI/atoms/MenuDropdown/MenuDropdown.interface.ts
  src/components/UI/atoms/Radio/Radio.component.tsx
  src/components/UI/atoms/Radio/children/RadioButton/RadioButton.component.tsx
  src/components/UI/atoms/UserMenuButtonAnalyst/UserMenuButtonAnalyst.module.scss
  src/components/UI/molecules/MenuIcon/MenuIcon.component.tsx
  src/components/UI/molecules/MenuIcon/MenuIcon.interface.ts
  src/components/UI/molecules/UserMenuAnalyst/UserMenuAnalyst.component.tsx
  src/components/UI/molecules/UserMenuAnalyst/UserMenuAnalyst.interface.ts
  src/components/UI/molecules/UserMenuAnalyst/UserMenuAnalyst.module.scss
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystOption/UserMenuAnalystOption.component.tsx
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystOption/UserMenuAnalystOption.module.scss
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystTitle/UserMenuAnalystTitle.component.tsx
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystTitle/UserMenuAnalystTitle.interface.ts
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystTitle/UserMenuAnalystTitle.module.scss
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystTitle/index.ts
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/index.ts
  src/components/UI/organism/HeaderAnalyst/HeaderAnalyst.component.tsx
  src/components/UI/organism/NavMenuAnalyst/NavMenuAnalyst.component.tsx
  src/components/UI/organism/NavMenuAnalyst/NavMenuAnalyst.interface.ts
  src/components/UI/organism/NavMenuAnalyst/NavMenuAnalyst.module.scss
  src/components/UI/organism/NavMenuAnalyst/children/NavMenuAnalystDivider/NavMenuAnalystDivider.module.scss
  src/components/UI/organism/NavMenuAnalyst/children/NavMenuAnalystOption/NavMenuAnalystOption.component.tsx
  src/components/UI/organism/NavMenuAnalyst/children/NavMenuAnalystOption/NavMenuAnalystOption.module.scss
  src/components/UI/organism/NavMenuAnalyst/children/NavMenuAnalystRegionModal/NavMenuAnalystRegionModal.component.tsx
  src/components/UI/organism/NavMenuAnalyst/children/NavMenuAnalystRegionModal/NavMenuAnalystRegionModal.module.scss
  src/components/UI/organism/NavMenuAnalyst/children/NavMenuAnalystRegionModal/children/NavMenuAnalystRegionModalContent/NavMenuAnalsytRegionModalContent.module.scss
  src/components/UI/organism/NavMenuAnalyst/children/NavMenuAnalystRegionModal/children/NavMenuAnalystRegionModalContent/NavMenuAnalystRegionModalContent.component.tsx
  src/components/UI/organism/NavMenuAnalyst/children/NavMenuAnalystRegionModal/children/NavMenuAnalystRegionModalContent/NavMenuAnalystRegionModalContent.interface.ts
  src/components/UI/organism/NavMenuAnalyst/children/NavMenuAnalystRegionModal/children/NavMenuAnalystRegionModalContent/index.ts
  src/components/UI/organism/NavMenuAnalyst/children/NavMenuAnalystRegionModal/children/index.ts
  src/components/UI/template/AnalystTemplate/AnalystTemplate.component.tsx
  src/components/UI/template/AnalystTemplate/AnalystTemplate.module.scss
  src/constants/stories/analyst.constants.ts
Labels: bug

#158 refactor: change method of passing width value to Drawer component
  src/components/UI/molecules/Drawer/Drawer.component.tsx
  src/components/UI/molecules/Drawer/Drawer.interface.ts
  src/components/UI/molecules/Drawer/drawer.module.scss
Labels: bug

#159 feat: add company list in analyst user menu
  src/assets/addSquareBlackOutline.svg
  src/assets/buildingSlashDarkBlueOutline.svg
  src/assets/mouseCircleDarkBlueOutline.svg
  src/assets/redoDarkBlue.svg
  src/components/UI/atoms/Link/Link.component.tsx
  src/components/UI/atoms/Link/Link.interface.ts
  src/components/UI/atoms/MenuDropdown/children/MenuDropdownList/MenuDropdownList.component.tsx
  src/components/UI/atoms/MenuDropdown/children/MenuDropdownList/MenuDropdownList.module.scss
  src/components/UI/atoms/UserMenuButtonAnalyst/UserMenuButtonAnalyst.component.tsx
  src/components/UI/atoms/UserMenuButtonAnalyst/UserMenuButtonAnalyst.interface.ts
  src/components/UI/molecules/Drawer/drawer.module.scss
  src/components/UI/molecules/UserMenuAnalyst/UserMenuAnalyst.component.tsx
  src/components/UI/molecules/UserMenuAnalyst/UserMenuAnalyst.constants.ts
  src/components/UI/molecules/UserMenuAnalyst/UserMenuAnalyst.interface.ts
  src/components/UI/molecules/UserMenuAnalyst/UserMenuAnalyst.module.scss
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystOption/UserMenuAnalystOption.component.tsx
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystOption/UserMenuAnalystOption.constants.ts
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystOption/UserMenuAnalystOption.interface.ts
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystOption/UserMenuAnalystOption.module.scss
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystOption/children/UserMenuAnalystOptionActions/UserMenuAnalystOptionActions.component.tsx
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystOption/children/UserMenuAnalystOptionActions/UserMenuAnalystOptionActions.interface.ts
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystOption/children/UserMenuAnalystOptionActions/index.ts
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystOption/children/UserMenuAnalystOptionDefault/UserMenuAnalystOptionDefault.component.tsx
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystOption/children/UserMenuAnalystOptionDefault/UserMenuAnalystOptionDefault.interface.ts
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystOption/children/UserMenuAnalystOptionDefault/UserMenuAnalystOptionDefault.module.scss
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystOption/children/UserMenuAnalystOptionDefault/index.ts
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystOption/children/UserMenuAnalystOptionHover/UserMenuAnalystOptionHover.component.tsx
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystOption/children/UserMenuAnalystOptionHover/UserMenuAnalystOptionHover.interface.ts
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystOption/children/UserMenuAnalystOptionHover/UserMenuAnalystOptionHover.module.scss
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystOption/children/UserMenuAnalystOptionHover/index.ts
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystOption/children/UserMenuAnalystOptionText/UserMenuAnalystOptionText.component.tsx
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystOption/children/UserMenuAnalystOptionText/UserMenuAnalystOptionText.interface.ts
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystOption/children/UserMenuAnalystOptionText/UserMenuAnalystOptionText.module.scss
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystOption/children/UserMenuAnalystOptionText/index.ts
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystOption/children/index.ts
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystTitle/UserMenuAnalystTitle.component.tsx
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystTitle/UserMenuAnalystTitle.interface.ts
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystTitle/UserMenuAnalystTitle.module.scss
  src/components/UI/molecules/UserMenuWrapperAnalyst/UserMenuWrapperAnalyst.interface.ts
  src/components/UI/molecules/UserMenuWrapperAnalyst/children/UserMenuWrapperAnalystDropdown/UserMenuWrapperAnalystDropdown.component.tsx
  src/components/UI/molecules/UserMenuWrapperAnalyst/children/UserMenuWrapperAnalystModal/UserMenuWrapperAnalystModal.component.tsx
  src/components/UI/organism/NavMenuDrawerAnalyst/NavMenuDrawerAnalyst.module.scss
  src/constants/icons.constants.ts
  src/constants/stories/analyst.constants.ts
  src/constants/stories/common.constants.ts
  src/utils/classNameManager/classNameManager.util.ts
Labels: bug, enhancement

#160 fix: fix menu dropdown overlap styles
  src/components/UI/atoms/MenuDropdown/MenuDropdown.component.tsx
  src/components/UI/atoms/MenuDropdown/MenuDropdown.module.scss
  src/components/UI/atoms/MenuDropdown/children/MenuDropdownList/MenuDropdownList.module.scss
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystOption/UserMenuAnalystOption.module.scss
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystOption/children/UserMenuAnalystOptionDefault/UserMenuAnalystOptionDefault.module.scss
  src/components/UI/molecules/UserMenuAnalyst/children/UserMenuAnalystOptions/children/UserMenuAnalystOption/children/UserMenuAnalystOptionText/UserMenuAnalystOptionText.module.scss
Labels: bug
